### ISSUE TITLE
Problem with "found duplicate"

### ISSUE THREAD

**Issue by JareckiB12** [HolgerHees/cloudsync#15]
I get the message:

[2015.03.23 13:00:04] - WARNING - found 1 duplicate item:
0ByfxY4INr5beNk80bV9vWFB4cVE - Foto/!Hubert/2/DCIM/102_COPY/DSC02273.JPG
try to run with '--clean=<path>'

and nothing i can do about it.
I tried:

./cloudsync.sh --backup /mnt/dobackupu -progress --clean=Foto/\!Hubert/2/DCIM/102_COPY/DSC02273.JPG --forcestart

the same without --forcestart, only --forcestart, full path (/mnt/dobackupu/Foto...), all combinations - nothing works, always ends with a message "try to run with..." What am i doing wrong and how to fix it?

cloudsync.config:

# your master password
PASSPHRASE=????

# use google drive as target
REMOTE_CONNECTOR=GoogleDrive

# google drive client id
GOOGLE_DRIVE_CLIENT_ID=???

# google drive client secret
GOOGLE_DRIVE_CLIENT_SECRET=???

# path to store the curently used client token
GOOGLE_DRIVE_CLIENT_TOKEN_PATH=./.cloudsync.token

# backup target on the remote server
GOOGLE_DRIVE_DIR=/backup

### {name} in *FILE properties is replaced with the currently used backup name ###

# used path to the cache file.
CACHEFILE=./.cloudsync_{name}.cache

# path to the log file
LOGFILE=./.cloudsync_{name}.log

# regex based exclude pattern
EXCLUDE=.*\\.git/.*|.*\\.svn/.*

# regex based include pattern
;INCLUDE=

# backup name
NAME=dobackupu

# behavior how to handle symbolic links
;FOLLOWLINKS=external

# behavior how to handle file duplications
DUPLICATE=skip

# Maximum number of stored histories
;HISTORY=0

**Comment by HolgerHees** [comment]
You can't use --backup together with --clean

You can use one of the following main options
--backup
--restore
--clean
--list

Additionally the "--clean" path parameter must be an absolute path. It is the location where the found duplicate files are moved.

**Comment by JareckiB12** [comment]
Thanks a lot, now it worked. This part of the explanation was very helpful:
"It is the location where the found duplicate files are moved." :)
