### ISSUE TITLE
--history option not working?

### ISSUE THREAD

**Issue by matrixagent** [HolgerHees/cloudsync#16]
Hi there,

I'm probably just misunderstanding how it works, in which case this is less of a bug report and more of a documentation issue.

Here are my steps:

```
./cloudsync.sh --backup /home/test/ --progress --history 3 --name blubb
echo "abcdefgh" > /home/test/trololo
./cloudsync.sh --backup /home/test/ --progress --history 3 --name blubb
rm /home/test/trololo
./cloudsync.sh --backup /home/test/ --progress --history 3 --name blubb
```

From how I understand the documentation, I should now still be able to retrieve the **/home/test/trololo** file. But how? I can't see it when I use ```--list```, and I can't find a folder/file with a date in the name anywhere on Google Drive. (I'm not sure if that newly constructed name is also encrypted, I just took a quick look at the source and saw that in case of the history-option there is a date added to the name.)

**Comment by HolgerHees** [comment]
The history option will create n-history folder.

That means. Every time you run cloudsync it creates a history folder of the current day. And instead of removing or overwriting old files, it will move the old file to this directory including the whole encrypted path.

You can restore this history by using the history folder name as your backup name.

I know, it is far away from being perfect. ☺

**Comment by matrixagent** [comment]
Thanks for getting back to me so quickly! I'm afraid I'm still unable to get it to work.

Two further questions for clarification:
1) Is there anything in the log/output indicating when a new history folder is created?
2) When browsing through the backup on Google Drive, should I be able to see a folder with the "current day" (formatted with "yyyy.MM.dd_HH.mm.ss", to be more specific) in its name?

As far as I understood your comment and the code, my above example should produce folders like
blubb
blubb 2015.04.21_10.08.33
blubb 2015.04.22_22.41.57
within the folder defined in *GOOGLE_DRIVE_DIR*, am I assuming correctly?

My example definitely shows ```[2015.04.21 09:54:07] - INFO - removed items: 1``` when I run cloudsync after the **rm /home/test/trololo** step, so the changed/removed item is recognized. However, I still only have the one single **blubb** folder within the *GOOGLE_DRIVE_DIR* afterwards and it seems there is no more copy of the **trololo** file anywhere. Am I still doing something wrong?

Thanks again for your time! :)

**Comment by HolgerHees** [comment]
I will investigate more time into this problem on next weekend.

**Comment by HolgerHees** [comment]
should work now with the latest beta release.
