### ISSUE TITLE
Support for Service Account authentication

### ISSUE THREAD

**Issue by alexhayes** [HolgerHees/cloudsync#17]
Is there any plan to support [Service Accounts](https://developers.google.com/identity/protocols/OAuth2?hl=en_US#serviceaccount)?

This functionality is vital for unattended installation/execution.

**Comment by HolgerHees** [comment]
and a huge thank you for improving this!

**Comment by alexhayes** [comment]
Thanks for accepting the PR and for the great work you've done on this project!
