### ISSUE TITLE
Parameter --no_delete

### ISSUE THREAD

**Issue by gelse** [HolgerHees/cloudsync#23]
I do a backup of a mounted smb directory.
After reboot (had to increase swap file size on the raspi) i started cloudsync, but forgot to mount the smb filesystem before.
The result was that cloudsync deleted 4 days of encryption/upload before i could react... ;-)
(And deletion means deletion, and not "move to trash"...)

To avoid something like this, i would suggest a --no-delete flag, which prevents deletion of folders on the remote target. Just update and create should work.

**Comment by HolgerHees** [comment]
you can use the --history= for that.

**Comment by gelse** [comment]
oh, ok, did not see that one. thanks - closed.
