### ISSUE TITLE
Difficulty for packaging

### ISSUE THREAD

**Issue by orschiro** [HolgerHees/cloudsync#7]
Hi @HolgerHees,

Many thanks for cloudsync. I am using Arch Linux and asked for help packaging it on the Arch Linux forums [1].

However, due to 3rd party dependencies, it is difficult to package. See this comment [2].

Is there any way to improve the support for packaging?

Regards,

Robert

[1] https://bbs.archlinux.org/viewtopic.php?pid=1494754#p1494754
[2] https://bbs.archlinux.org/viewtopic.php?pid=1496283#p1496283

**Comment by HolgerHees** [comment]
Hi Robert,

just follow the instruction on the wiki page.

https://github.com/HolgerHees/cloudsync/wiki/Maven-HowTo

after running "mvn install" you will find compressed files inside the folder "target". They contain everything you need. Also the dependencies.

Best,

Holger

**Comment by HolgerHees** [comment]
does it answer your question?

**Comment by orschiro** [comment]
Yes, it does. And hopefully also for the other packagers.

Thanks!

Lazy type mode on from mobile
