### ISSUE TITLE
not working on arm?

### ISSUE THREAD

**Issue by snapek** [HolgerHees/cloudsync#8]
I'm giving cloudsync a try on a Raspberry Pi, and seem to be hitting a wall.  I assume it's a platform issue, but I may be wrong.

when calling the cloudsync.sh the results are ;

$ ./cloudsync.sh --backup /mnt/backup/Photos/

./cloudsync.sh: 10: ./cloudsync.sh: cannot open 1.7: No such file

./cloudsync.sh: 10: ./cloudsync.sh: [[: not found

Error: Could not find or load main class cloudsync.Cloudsync

**Comment by HolgerHees** [comment]
Seams to be a shell script problem.

It works fine in my bash shell. What is your default shell?

If it's another one try to change the first line from

#!/bin/sh

to

#!/bin/bash

**Comment by snapek** [comment]
Yup, that resolved that issue.  Now when run I run into the following error;

Error: Could not find or load main class cloudsync.Cloudsync

**Comment by HolgerHees** [comment]
You try to use the cloned git repository. In this case you must run the maven install process. To do this just follow the instructions from the wiki.

https://github.com/HolgerHees/cloudsync/wiki/Maven-HowTo

But you can also try the binary release.

**Comment by snapek** [comment]
Ah, right, sorry about that!

Thanks again.

**Comment by HolgerHees** [comment]
No problem. It was a hint for me that i should improve the documentation. :-)

**Comment by snapek** [comment]
This project is absolutely fantastic, and was *exactly* what I've been looking for, I wanted to thank you again.  The only other option for encrypted backups to google drive is duplicati, which is hardly a suitable solution.

Many thanks! :)
